// <auto-generated />
using System;
using GerenciadorDeTarefaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorDeTarefaApi.Migrations
{
    [DbContext(typeof(TarefaContext))]
    partial class TarefaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerenciadorDeTarefaApi.Models.Tarefa", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTarefa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoTarefa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusTarefa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TituloTarefa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTarefa");

                    b.ToTable("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
